WIP

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -320,6 +320,69 @@ jobs:
           docker_account: ${{ secrets.DOCKERHUB_PULL_USER }}
           docker_token: ${{ secrets.DOCKERHUB_PULL_TOKEN }}
 
+  usb-boot:
+    name: USB Boot Priority
+    env:
+      JOB_NAME: USB Boot Priority
+    needs: [determine-runner]
+    runs-on: ${{ fromJSON(needs.determine-runner.outputs.runner_virt) }}
+    steps:
+      - name: Print Public IP Address
+        run: |
+          echo "Public IP Address of the runner:"
+          curl -s https://api.ipify.org
+        shell: bash
+      - name: Check job status from previous attempt
+        id: prev_attempt
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+          FULL_JOB_NAME: ${{ env.JOB_NAME }}
+        run: |
+            PREV_ATTEMPT=$((${{ github.run_attempt }} - 1 ))
+            # For the first attempt, we don't need to check the previous attempt, just set conclusion to 'skipped'
+            if [ "$PREV_ATTEMPT" -le 0 ]; then
+                echo "conclusion=skipped" >> "$GITHUB_OUTPUT"
+                exit 0
+            fi
+            prev_conclusion=$(
+                gh api \
+                -X GET \
+                repos/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}/attempts/${PREV_ATTEMPT}/jobs \
+                -q ".jobs[] | select(.name | contains(\"${{ env.FULL_JOB_NAME }}\")) | .conclusion"
+            )
+            if [ -z "$prev_conclusion" ]; then
+                echo "Could not find matching job in attempt ${PREV_ATTEMPT}" >&2
+                exit 1
+            fi
+            echo "conclusion=$prev_conclusion" >> "$GITHUB_OUTPUT"
+      - name: Dockerhub Login
+        if: ${{ github.event.repository.full_name == 'lf-edge/eve' && steps.prev_attempt.outputs.conclusion != 'success' }}
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_PULL_USER }}
+          password: ${{ secrets.DOCKERHUB_PULL_TOKEN }}
+      - name: Get code
+        if: steps.prev_attempt.outputs.conclusion != 'success'
+        uses: actions/checkout@v4.1.1
+        with:
+          repository: "lf-edge/eden"
+          ref: ${{ inputs.eden_version }}
+          path: "./eden"
+      - name: Run tests
+        if: steps.prev_attempt.outputs.conclusion != 'success'
+        uses: ./eden/.github/actions/run-eden-test
+        with:
+          file_system: "ext4"
+          tpm_enabled: false
+          suite: "usb-boot.tests.txt"
+          eve_image: ${{ inputs.eve_image }}
+          eve_log_level: ${{ inputs.eve_log_level }}
+          eve_artifact_name: ${{ inputs.eve_artifact_name }}
+          artifact_run_id: ${{ inputs.artifact_run_id }}
+          docker_account: ${{ secrets.DOCKERHUB_PULL_USER }}
+          docker_token: ${{ secrets.DOCKERHUB_PULL_TOKEN }}
+          usb_boot_enabled: 'true'
+
   eve-upgrade:
     name: EVE Upgrade
     env:
